//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUMTool_R {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YUMTool_R.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Missing Moon Archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypeMM {
            get {
                return ResourceManager.GetString("ArchiveTypeMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing Moon Archive Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypeMM_Directory {
            get {
                return ResourceManager.GetString("ArchiveTypeMM_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perfect Sun Archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypePS {
            get {
                return ResourceManager.GetString("ArchiveTypePS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perfect Sun Archive Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypePS_Directory {
            get {
                return ResourceManager.GetString("ArchiveTypePS_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wanderling Star Archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypeWS {
            get {
                return ResourceManager.GetString("ArchiveTypeWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wanderling Star Archive Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveTypeWS_Directory {
            get {
                return ResourceManager.GetString("ArchiveTypeWS_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsName {
            get {
                return ResourceManager.GetString("ColumnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsSize {
            get {
                return ResourceManager.GetString("ColumnsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsType {
            get {
                return ResourceManager.GetString("ColumnsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressing...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DecompressProgress {
            get {
                return ResourceManager.GetString("DecompressProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the file: {0}
        ///This file is not an idolm@ster SP archive.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArchive {
            get {
                return ResourceManager.GetString("ErrorArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the directory: {0}
        ///This directory is not an idolm@ster SP archive directory.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArchiveFolder {
            get {
                return ResourceManager.GetString("ErrorArchiveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the file: {0}
        ///This file is not an genuine idolm@ster SP archive file.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArchiveNotGenuine {
            get {
                return ResourceManager.GetString("ErrorArchiveNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///{0} Decompressed failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDecompressed {
            get {
                return ResourceManager.GetString("ErrorDecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the directory: {0}
        ///This directory doesn&apos;t contain {1}.index file.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIndex {
            get {
                return ResourceManager.GetString("ErrorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///No offset value is specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOffsetLength {
            get {
                return ResourceManager.GetString("ErrorOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perl is not installed on this computer.
        ///Please install ActivePerl or Strawberry Perl and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPerlNotFound {
            get {
                return ResourceManager.GetString("ErrorPerlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///{0} Recompressed failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRecompressed {
            get {
                return ResourceManager.GetString("ErrorRecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Archive Folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FbdArchiveOpenTitle {
            get {
                return ResourceManager.GetString("FbdArchiveOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Save Folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FbdArchiveSaveTitle {
            get {
                return ResourceManager.GetString("FbdArchiveSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSizeText {
            get {
                return ResourceManager.GetString("FileSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP, Archive (YUMFILE_*.BIN)|YUMFILE_1.BIN;YUMFILE_2.BIN;YUMFILE_3.BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterArchive {
            get {
                return ResourceManager.GetString("FilterArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP, Missing Moon Archive (YUMFILE_3.BIN)|YUMFILE_3.BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterMM {
            get {
                return ResourceManager.GetString("FilterMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP, Perfect Sun Archive (YUMFILE_1.BIN)|YUMFILE_1.BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPS {
            get {
                return ResourceManager.GetString("FilterPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP, Wanderling Star Archive (YUMFILE_2.BIN)|YUMFILE_2.BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterWS {
            get {
                return ResourceManager.GetString("FilterWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open IDOLM@STER SP Archive Folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderBrowserDialogArchive {
            get {
                return ResourceManager.GetString("FolderBrowserDialogArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ActivePerl found: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundActivePerl {
            get {
                return ResourceManager.GetString("FoundActivePerl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StrawberryPerl found: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundStrawberryPerl {
            get {
                return ResourceManager.GetString("FoundStrawberryPerl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application version is the latest. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Latested {
            get {
                return ResourceManager.GetString("Latested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Moving... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveText {
            get {
                return ResourceManager.GetString("MoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open IDOLM@STER SP Archive Binary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileDialogArchive {
            get {
                return ResourceManager.GetString("OpenFileDialogArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is being decompressed: {1} / {2} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressDecompressed {
            get {
                return ResourceManager.GetString("ProgressDecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialized... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressInitialize {
            get {
                return ResourceManager.GetString("ProgressInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is being recompressed: {1} / {2} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressRecompressed {
            get {
                return ResourceManager.GetString("ProgressRecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded the archive: {0}
        ///Size: {1}
        ///Type: {2}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadedArchive {
            get {
                return ResourceManager.GetString("ReadedArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded the archive folder: {0}
        ///Size: {1}
        ///File count: {2}
        ///Type: {3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadedArchiveFolder {
            get {
                return ResourceManager.GetString("ReadedArchiveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recompressing...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecompressProgress {
            get {
                return ResourceManager.GetString("RecompressProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Started.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunningApp {
            get {
                return ResourceManager.GetString("RunningApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save IDOLM@STER SP Archive Binary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileDialogArchive {
            get {
                return ResourceManager.GetString("SaveFileDialogArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompression is complete.
        ///Number of decompressed files: {0} files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessDecompressed {
            get {
                return ResourceManager.GetString("SuccessDecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessProgress {
            get {
                return ResourceManager.GetString("SuccessProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recompression is complete.
        ///Number of recompressed size: {0} bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessRecompressed {
            get {
                return ResourceManager.GetString("SuccessRecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///File: {0} is not a genuine archive file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedArchiveFileSize {
            get {
                return ResourceManager.GetString("UnexpectedArchiveFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///File count mismatch in this directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedFileCountMismatch {
            get {
                return ResourceManager.GetString("UnexpectedFileCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///File: {0}
        ///This index file has corrupted path information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedIndexCorrupted {
            get {
                return ResourceManager.GetString("UnexpectedIndexCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///The {0}.index file doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedIndexNotFound {
            get {
                return ResourceManager.GetString("UnexpectedIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///Path: {0}
        ///The directory with the path described in the index file was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedIndexNotFoundPath {
            get {
                return ResourceManager.GetString("UnexpectedIndexNotFoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///This file is not an archive file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedNotArchive {
            get {
                return ResourceManager.GetString("UnexpectedNotArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///This directory is not an archive directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedNotArchiveDirectory {
            get {
                return ResourceManager.GetString("UnexpectedNotArchiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application can be updated.
        ///Do you want to open the site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifyed.
        ///File count: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerifyCount {
            get {
                return ResourceManager.GetString("VerifyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifyed.
        ///Size: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerifySize {
            get {
                return ResourceManager.GetString("VerifySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file already exists in the specified directory.
        ///If you continue, all files in the directory will be lost.
        ///Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningExist {
            get {
                return ResourceManager.GetString("WarningExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
